name: 'walmart'
version: '1.0.0'

profile: 'walmart'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  walmart:
    silver_tech:
      +materialized: incremental
      +schema: silver_tech
    silver_biz:
      +materialized: table
      +schema: silver_biz
    gold:
      +schema: gold
      +materialized: table        # default for everything in gold
      ephemeral:
        +materialized: ephemeral  # only models in models/gold/ephemeral/
      fact:
        +materialized: table