sources:
  - name: walmart
    database: walmart
    schema: bronze
    tables:
      - name: customers
      - name: employees
      - name: order_items
      - name: orders
      - name: products
      - name: stores
